@startuml
skinparam rectangle {
    BackgroundColor White
    BorderColor Black
    RoundCorner 0
}

rectangle "C:/" as C
rectangle "LOBODOMALTE" as ROOT

C --> ROOT

rectangle "adriana.tanaka\nAdministradores: Controle Total\nadriana.tanaka: modificar, ler &\nexecutar, listar conteúdo da pasta,\nleitura, gravar\nCota: 300MB" as U1

ROOT --> U1
@enduml
